CREATE TABLE STUDENTS (
  Id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL
);


INSERT INTO STUDENTS VALUES (1, 'Иван', 18);
INSERT INTO STUDENTS VALUES (2, 'Петр', 22);
INSERT INTO STUDENTS VALUES (3, 'Анна', 35);
INSERT INTO STUDENTS VALUES (4, 'Юлия', 18);
INSERT INTO STUDENTS VALUES (5, 'Николай', 36);


SELECT * FROM STUDENTS WHERE age > 18;